eecs485staff/primer-spec

_layouts/spec.html, _sass/spec/index.scss
The current spec theme is not mobile-friendly. When the sidebar opens, the content width changes — this means that when a user clicks a link in the sidebar and then hides the sidebar, the content of the page shifts, leaving the user confused about where they are in the document. (You can try this on mobile on one of the current specs.)
This PR makes the sidebar overlays on top of the content on small screens, so that the position of the content doesn't change every time the sidebar is toggled.
Also modified the layout to use GitHub Primer CSS utility classes instead of defining them separately in `spec/index.scss`.
=> Enhanced mobile experience

README.md, _layouts/spec.html, _sass/jekyll-theme-primer.scss, _sass/spec/base.scss, _sass/spec/bella.theme.scss, _sass/spec/default.theme.scss, _sass/spec/metro.theme.scss, _sass/spec/xcode-dark.theme.scss, assets/css/theme_bella.scss, assets/css/theme_default.scss, assets/css/theme_metro.scss, assets/css/theme_xcode-dark.scss, assets/js/html-table-of-contents.js
Given that we've already created a wrapper for displaying the spec, I think theme support is the next logical step! This PR has a lot of changes — for the subthemes to be written efficiently, I needed to change how the code was organized. The code is now better organized and documented than before, so hopefully maintenance will be a bit easier.
_Tl;dr: See the live demo at http://www-personal.umich.edu/~seshrs/primer-spec-develop/. Then see the **"Maintenance notes and questions"** section at the end of this note._
- Modified visual appearance of sidebar:
- Sidebar is wider with larger text.
- Sidebar toggle button now uses the recognizable "hamburger" icon.
- Highlighted section in the sidebar is the section at the top of the viewer's screen. (Previously, it was whatever section that was …
=> [Feature] Theme Support (and better UI)

.travis.yml, Gemfile, README.md, jekyll-theme-primer-spec.gemspec, script/cibuild, script/validate-html
("Copy" of #5.)
A maintenance PR, as described in https://github.com/eecs485staff/primer-spec#keeping-this-theme-up-to-date-with-primer. Also fixes the build failure.
Also updated the maintenance instructions in the README to detail the steps I took to resolve merge conflicts. (I created a new branch and cherry-picked/merged commits from upstream.) I'm not certain if there's a more elegant approach, I'm open to other suggestions.
=> [Maintenance] Merge from upstream

_layouts/spec.html
When a visitor clicks an internal link, default browser behavior is used on non-small screens. The custom scrolling code only runs on mobile, and only because we have to account for the opaque "topbar" that would otherwise hide the content that needs to be displayed.
Fixes #4.
=> [Bugfix] Fixed internal link history behavior

Gemfile
Jekyll 3.8.6 seems to fail with the newest major release of Faraday (1.0.0). As suggested in github/personal-website#166, this PR ensures that the older version of Faraday is used in conjunction with Jekyll. (This should fix the Travis failures.)
=> [Hotfix] Require specific Faraday version

.githooks/pre-commit, _layouts/spec.html, index.md, script/build, script/ci-site-preview-build, script/cibuild, script/server, webpack.config.js
This PR allows Primer Spec to be built with a specific `base_url`. This is achieved by adding a new script `ci-site-preview-build`, and updating the Webpack and Jekyll options to use this specified base URL during the build.
The changes in this PR make it possible for the Primer Spec Preview app to generate a site preview with the latest CSS and JS changes from the PR. Ideally, the preview generated in the "checks" section of this PR should have a preview that uses locally-built JS and CSS files.
=> [Enhancement] Add staging options to build scripts

_sass/spec/base.scss
On Firefox and Safari, any LaTeX on the page rendered above the settings modal. (This also happened to the checkboxes at the end of EECS 280 specs.) Additionally, on mobile, it is difficult to close an open sidebar when the settings modal is open.
This commit updates the z-indices of Primer Spec components to reliably ensure correct visual ordering. The Sidebar must *always* appear above the Topbar, which must always appear above the Settings modal. When shown, the Settings modal should appear on top of any main content (including LaTeX and checkboxes).
1) Visit PREVIEW#54 on Firefox or Safari desktop, scroll to the "LaTeX Support" section near the bottom of the page. Open the Settings modal. The LaTeX should not be visible.
2) Visit the Primer Spec site preview on a mobile browser. Open …
=> Fix z-index layering of components

_layouts/spec.html, _sass/spec/base.scss
This PR fixes two rendering issues related to LaTeX:
- LaTeX used to render on top of the Topbar on mobile if the Settings pane wasn't shown. This commit fixes the Topbar z-index to *always* be on top of main content.
- On Safari, LaTeX blocks would annoying scroll independently on the page (despite having no real overflow). This commit specifies that vertical overflow should always be hidden on LaTeX.
=> Fix LaTeX rendering

_layouts/spec.html, docs/USAGE_ADVANCED.md
As far as I can tell, preloading scripts has the same effect as using the [`defer` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#:~:text=This%20Boolean%20attribute%20is%20set%20to%20indicate%20to%20a%20browser%20that%20the%20script%20is%20meant%20to%20be%20executed%20after%20the%20document%20has%20been%20parsed,%20but%20before%20firing%20DomContentLoaded.). Using `defer` makes the non-Jekyll setup easier, so we might as well switch to that.
=> Use script defer instead of preload

docs/USAGE_ADVANCED.md
As discussed in #58, it's possible to parse GitHub Pages MarkDown files with GFM instead of "regular" MarkDown. This PR adds instructions to enable GFM parsing on GitHub pages in USAGE_ADVANCED.md.
The only caveat is that it would be impossible to render local previews of Primer Spec (since the `_config.yml` option is only recognized by GitHub Pages). I've included the caveat as a "warning" in the docs.
Resolves #58.
=> Add GFM instructions to USAGE_ADVANCED

README.md, docs/USAGE_ADVANCED.md
GitHub Pages enables the [`jemoji` plugin](https://github.com/jekyll/jemoji) by default on GH Pages sites without a config. There's no harm in recommending Primer Spec users to enable this plugin — GitHub-flavored emoji can be quite convenient!
=> Add jemoji to receommended plugins

_layouts/default.html, _layouts/spec.html, docs/USAGE_ADVANCED.md
EECS 485 has a custom favicon, and other courses' staff may be considering adding favicons to help students find the project-spec tabs in their browsers. This PR allows course staff to configure favicons to be used for all pages on their site.
I also think it would be great to see this feature make its way to the original Primer theme. I've opened pages-themes/primer#42 to request adding this support.
Pull the branch locally.
1) Add the following line to `_config.yml`:
```yml
favicon: https://eecs485staff.github.io/eecs485.org/favicon.ico
```
Run `script/server` and visit http://localhost:4000 —- the site's favicon should display in the browser tab list.
2) Remove the line from `_config.yml` and restart `script/server`. Refresh the page on your browser, and notice that the browser uses a …
=> Add support for favicons

_sass/spec/base.scss, demo/long-headings.md
I noticed that if a heading is extra-long and cannot be broken by default Unicode text-break rules, the *entire* Sidebar's width increases and becomes horizontally scrollable. Not only does this feel like a weird experience, but this also looks bad!
Here's an example from an EECS 441 spec: https://eecs441.eecs.umich.edu/asns/lab1-kotlinImages#a-known-issues-with-mediastoreactionvideocapture
This PR proposes to add an `overflow` property to all Sidebar heading items. This means that the width of a heading item *will not* affect the Sidebar's width; instead, the heading item **alone** will become scrollable. (This approach is similar to how code-blocks and LaTeX blocks are scrollable on small screens.)
I think this is acceptable given that most specs do not feature long headings. However, …
=> [RFC] Prevent long headings from increasing Sidebar's width

_sass/spec/base.scss, demo/long-headings.md
I used the `overflow: scroll` CSS property on certain wide/tall elements so that their width/height do not affect the width/height of their parent elements. For instance, this property was applied to each ToC item in the Sidebar so that any single wide ToC item would not cause the entire Sidebar to scroll horizontally.
Unfortunately, I should have been using `overflow: auto` instead so that scrollbars are hidden when not necessary. I don't know why I forgot about that, but @sbeinlich reminded me while refactoring the eecs485.org website. (Thanks @sbeinlich!)
This PR changes all occurrences of `overflow: scroll` to `overflow: auto`.
Visit PREVIEW#86 on a Windows computer. I used Chrome 86 on Windows 10 via [browserstack.com](https://www.browserstack.com).
**Before** (note the ugly …
=> Hide unnecessary scrollbars on Windows

README.md, docs/CONTRIBUTING.md, docs/DEV_README.md
My hope is that the open-source community and the students and staff who use Primer Spec can contribute (and even maintain) the theme. However, I understand that Primer Spec might be a bit intimidating and confusing to analyze. There are several different systems working together in this repository, and context about Jekyll, JavaScript, CSS and build systems is needed to truly understand it all. (I also hope that I don't end up as a knowledge-silo 😛)
The `DEV_README` file is an attempt to provide context about the way Primer Spec works. I'm not entirely if it's helpful enough, but I'm hoping that it's a fair starting point for anyone who's interested in proposing changes to this project.
=> Add Dev Onboarding notes

.travis.yml
PR's currently run both a PR Travis build as well as a branch build. We only need the PR build.
=> Don't run Travis for pushes to every branch

.github/workflows/verify-pr-base-branch.yml, .github/workflows/verify-pr-target-branch.yml
As discussed in #109, we need to make `master` the default branch. But this means that if contributors propose pull requests to this repo, their PRs will target `master` by default!
This PR adds a GH Actions workflow to change the base branch of a PR if it was opened to any branch besides `develop`.
Closes #109. CC @awdeorio, @jadchaar 
To test, I intentionally opened this PR on `master`. If all goes, well, GH Actions should change the base branch and comment on this PR.
EDIT: It did! 🚀
=> Disallow PRs to any branch besides develop

.githooks/pre-commit, .github/workflows/release.yml, docs/CONTRIBUTING.md, docs/DEV_README.md, script/version, src_js/Config.ts, webpack.config.js
This PR removes the need for committing an up-to-date version of the JS with every commit. Instead, we will use a GH Actions workflow to prepare the `master` branch for release!
To achieve this:
- I added a new GH Actions workflow to freeze the version, build the latest JS and sync `master` branch with `develop`. This workflow is initiated manually from the GH Actions tab.
- I updated the pre-commit hook to ensure that the `assets` directory is not updated in any commit (except in the workflow).
I haven't tested the workflow file, but I guess we'll know when we release v1.5.0 in a few weeks 😃
=> Release improvements

_layouts/default.html, _layouts/spec.html, docs/USAGE_ADVANCED.md
Google Analytics has deprecated the use of `analytics.js` and instead encourages users to use `gtag.js`. This change is backwards-compatible because `gtag.js` supports both the newer `G-xxxx` measurement ID and the older `UA-xxxx` tracking ID formats.
I will cherry-pick these commits to current `master` and release the change as v1.4.2. CC @eecs441staff
Closes #120.
=> Update Google Analytics snippet to use gtag.js

_sass/spec/base.scss, demo/callouts.md, docs/USAGE_ADVANCED.md
Yet another Callouts PR! 😅 
I gave some thought to the accessibility of callouts, and I realized that the default callout API "discouraged" the use of icons for the sake of flexibility — it was possible to use any icon-variant with any callout-variant.
However, I can't think of any good reason why one would want to use the triangular-warning-icon with a green-success callout. Further, excluding icons (or using the wrong icon) can be particularly confusing for students with visual impairments and who are unable to distinguish certain colors.
Hence, this PR removes the ability to customize the icon per-callout, and _always_ displays an icon for each callout. See the new preview page: https://preview.seshrs.ml/previews/eecs485staff/primer-spec/122/demo/callouts.html
---
PS: The callouts …
=> Always include icons in Callouts

_sass/spec/base.scss, demo/callouts.md, src_js/subthemes/Subtheme.ts, src_js/subthemes/definitions/common_dark_theme_colors.ts, src_js/subthemes/definitions/xcode_civic.theme.ts
This PR adds a `neutral` callout variant as the default styling for callouts. If a `<div>` or `<p>` has class-name `primer-spec-callout`, it uses the neutral colors by default.
A `neutral` callout is useful when specs need to highlight some information, but the `info` variant emphasizes the content too strongly.
Visit the callouts demo page: https://preview.seshrs.ml/previews/eecs485staff/primer-spec/123/demo/callouts.html
Here's what the `neutral` callouts look like in light mode:
And in dark mode:
---
Thanks @eecs441staff for the feature request and for suggesting what GitHub colors could be used! 😃
=> [Callouts] Add neutral variant

.github/workflows/cibuild.yml, .github/workflows/release.yml, README.md, docs/CONTRIBUTING.md, docs/DEV_README.md, docs/USAGE_ADVANCED.md, script/cibuild
As part of #126 (renaming the `master` branch to `main` branch), I set up a new branch called `main`. This PR achieves the following:
1. Keep the new `main` branch in sync with `master` (until `master` has been deleted)
2. All references to `master` in the docs need to be updated.
=> Update docs and workflow references to master branch, sync main branch

_sass/spec/base.scss, src_js/subthemes/Subtheme.ts, src_js/subthemes/definitions/common_dark_theme_colors.ts
While attempting to fix dark mode colors in eecs485staff/p5-search-engine#487, I realized that I had removed contrastive table-row styling two years ago. At the time, I didn't know what colors to use for dark mode — that wasn't a great reason to remove contrastive table row styles 😅
Now that GitHub supports dark mode natively, I decided to take a second look. I don't like GitHub's new contrast-color in dark mode, I think it doesn't look visually distinct enough. After playing around with a color picker, I ended up with the following design:
<table>
<tr><th>Light Mode</th><th>Dark Mode</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Suggestions are appreciated! CC @bellakiminsun
**NOTE**: I plan to cherry-pick this change to the FA2021 release so that it can be used by EECS 485 P5 this …
=> Use contrastive colors for table rows

demo/enhanced-code-blocks.md, src_js/components/main_content/useEnhancedCodeBlocks.tsx
Closes #137.
Before this PR, Primer Spec would `slugify` the title of the code block to generate an Anchor ID (a hyperlink directly to the code block). Unfortunately, I failed to realize that multiple code blocks on the same page could have the same ID 🤦‍♂️ 
In this PR, we also attach the unique "codeblock ID" to the anchor so that the anchors are guaranteed to be unique.
Click the titles of codeblocks in the "Enhanced Code Blocks" demo page in the preview for this PR. Notice that the anchors contain a number referencing the codeblock's ID.
https://preview.sesh.rs/previews/eecs485staff/primer-spec/141/demo/enhanced-code-blocks.html
=> Assign unique anchor ID to codeblockcks with the same title

src_js/subthemes/definitions/common_dark_theme_colors.ts
As title. Closes #139.
| Before | After |
|-------|---------|
| ![image](https://user-images.githubusercontent.com/12139762/146876140-5d9029da-6a3a-4b57-81d9-408cafd65357.png)  | ![image](https://user-images.githubusercontent.com/12139762/146876038-759f1702-96be-40fa-af42-69383d8f6de1.png) |
I also verified that other inline code blocks look unchanged.
=> Remove border from inline-code in tables in dark mode

_sass/spec/base.scss
I noticed a bug in Firefox when the screen / browser window is "small" and Primer Spec is using a dark mode theme. The issue was that the dark-colored "enhanced code block" wasn't explicitly marked as "full-width". It looks like Chrome uses a more convenient default, whereas Firefox does not.
This PR fixes the colors by making the code block container table as full-width.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img width="865" alt="Screen Shot 2022-01-10 at 7 53 44 PM" src="https://user-images.githubusercontent.com/12139762/148863206-ff3f6b35-7b3f-40a3-9a6d-9c68b024ca18.png"></td>
<td><img width="867" alt="Screen Shot 2022-01-10 at 7 54 06 PM" src="https://user-images.githubusercontent.com/12139762/148863241-18d42b88-8dc2-4e73-bbdf-c95e8e5fd6cd.png"></td>
</tr>
</table>
=> [Code blocks][Firefox-specific] Fix dark mode colors on small screens

src_js/components/main_content/useEnhancedCodeBlocks.tsx
While browsing [EECS 183 Project 1](https://eecs183.github.io/p1-recipes/#project-1-style-rubric), I saw the following code block that had a differently-styled first-line:
```html
<pre><code>if (loaves == 1) {
//do something
} else if (loaves == 2) {
//do something else
} // and so on</code></pre>
```
I had not anticipated that a manual `<pre>` block might also contain a single `<code>` block child. This commit modifies the code-block detection algorithm to look ignore the inner `<code>` block if applicable.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img width="634" alt="Screen Shot 2022-01-11 at 11 58 42 AM" src="https://user-images.githubusercontent.com/12139762/148990975-ef58f6d1-10b4-4c63-81b5-634fd4c86624.png"></td>
<td><img width="647" alt="Screen Shot 2022-01-11 at …
=> [Code Blocks] Allow <pre> to contain <code> child

.prettierignore, _sass/spec/base.scss, _sass/spec/default_theme.scss, demo/images.md, docs/USAGE_ADVANCED.md, index.md, src_js/components/main_content/index.tsx, src_js/subthemes/Subtheme.ts, src_js/subthemes/definitions/common_dark_theme_colors.ts
This PR introduces two changes to images:
- All images render with a subtle border. I personally find it super-annoying to see images that just blend with the page background, which is why I decided to make this a default Primer Spec feature.
- If pages want to opt-out of image borders, add the class `no-border` to the image.
- If you add the class `invert-colors-in-dark-mode`, Primer Spec will automatically invert the colors when the user views the page in dark-mode. This especially works great for diagrams!
Preview the Images demo in the PR preview site: https://preview.sesh.rs/previews/eecs485staff/primer-spec/158/demo/images.html
Light mode:
> <img width="1048" alt="image" src="https://user-images.githubusercontent.com/12139762/156948491-9e2070a6-8264-4d41-b046-77b7af1371d2.png">
Dark …
=> [Images] Auto-invert colors, add subtle border

index.md, src_js/components/sidebar/TableOfContents.tsx
Fixes #160.
Here's how we generated heading labels in the Table of Contents before this PR: If a heading contained multiple HTML elements (for instance, formatting), we ignored most of those elements and only used text nodes and codeblocks. However, this was a mistake — @marcus-darden pointed out that headings can have italics and other formatting.
This PR updates the heading-label generation logic to preserve almost all formatting within headings (except for the AnchorJS link).
I updated the "Install the dependencies" heading in the Project 0 demo spec (`index.md`). Visit the preview URL and observe the label in the sidebar.
Preview URL: https://preview.sesh.rs/previews/eecs485staff/primer-spec/164/
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table> …
=> Retain most HTML elements in heading label in Table of Contents

_config.yml, _layouts/spec.html, _sass/spec/base.scss, demo/enhanced-code-blocks.md, demo/page-configuration-options.md, docs/USAGE_ADVANCED.md, src_js/Config.ts, src_js/components/main_content/types.ts, src_js/components/main_content/useEnhancedCodeBlocks.tsx, src_js/global.d.ts
Resolves #159.
@awdeorio noted that line numbers don't work great for all code blocks. (@eecs441staff shared the same feedback with me earlier this year.)
This PR introduces a new code-block "variant" called **`no-line-numbers`**. This variant is exactly identical to `enhanced`, except that line numbers aren't shown. (Other "enhanced" features are retained — copying the block, clicking a line, highlighting lines, etc. continue to work!)
With these changes, the `data-variant` attribute on code blocks supports these three options:
- **`enhanced`** (the default)
- **`no-line-numbers`** (identical to `enhanced` but without line numbers)
- **`legacy`** (the old style)
Additionally, this PR adds a new page-wide/site-wide configuration option `defaultCodeblockVariant` that can be used to set the …
=> [Code Blocks] `no-line-numbers` variant

_sass/spec/base.scss, demo/images.md, docs/MARKDOWN_TIPS.md, src_js/components/main_content/index.tsx, src_js/subthemes/createSubtheme.ts
Closes #163.
GitHub allows users to specify light-mode and dark-mode variants of their image [by appending a directive to the end of the image URL](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to). For instance:
```html
```
This PR brings the same feature to Primer Spec! I've also updated the docs and demo pages to describe how to optimize your website's images in dark mode.
**Demo URL**: https://preview.sesh.rs/previews/eecs485staff/primer-spec/170/demo/images.html#option-2-show-images-only-in-certain-theme-mode
Switch the Primer Spec theme settings between light mode and dark mode. Notice that the light-mode logo is only shown in light mode, and …
=> [Images] Allow defining light/dark mode variants of images like GitHub

demo/enhanced-code-blocks.md, docs/MARKDOWN_TIPS.md, src_js/components/main_content/useEnhancedCodeBlocks.tsx
Closes #169. (Thanks for the feature request @sugihjamin!)
@sugihjamin noted that there is value in copying all *commands* in a `console` code block with a single button. This PR modifies the generic "Copy" button's behavior only in `console` blocks:
- The label says "Copy all commands".
- Clicking it only copies commands (without the command prompt symbols), and skips console output lines.
Here's a screen recording demonstrating what it feels like:
https://user-images.githubusercontent.com/12139762/163686126-d146c7c2-ff2f-4e4e-a5e5-db205d38cc6b.mov
*NOTE: While the functionality works okay for `pycon` blocks, it isn't perfect because it doesn't preserve the whitespace in front of each line. I will open up a separate issue (#175) to track this, but I don't know how to fix it yet.*
Visit …
=> [Enhanced Codeblocks] Show 'Copy all commands' button for console codeblocks

src_js/components/main_content/useEnhancedCodeBlocks.tsx
Fixes #178.
I accidentally introduced the bug described in #178 while zealously trying to remove additional whitespace at the end of codeblocks. In retrospect, Primer Spec shouldn't remove any leading/trailing whitespace in code blocks, the spec authors should be responsible for that!
Thanks @jackphong for reporting the bug!
=> Do not trim codeblock contents

src_js/components/main_content/index.tsx, src_js/utils/hooks/useWindowLoaded.ts
Closes #187.
While researching potential causes for #187, I found that the MermaidJS documentation suggests rendering diagrams only after the page finishes loading. [(Source)](https://mermaid-js.github.io/mermaid/#/usage?id=labels-out-of-bounds)
It also turns out that the `useEffect` hook fires after the first render _while the JS script is executing_ — however, CSS resources and fonts may not have finishes loading by that time. (More specifically, [`document.readyState`](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState) may be `interactive`.)
This PR makes Primer Spec re-render Mermaid diagrams _again_ after the window "loads". This second re-render should fix any labels that were clipped.
<details>
<summary>Why not skip the first Mermaid render and simply render once …
=> Re-render Mermaid diagrams on window load

_layouts/spec.html, package-lock.json, src_js/main.tsx, src_js/utils/hooks/print.ts, src_js/utils/hooks/usePrefersDarkMode.ts, src_js/utils/hooks/useSmallScreen.ts, src_js/utils/hooks/useWindowLoaded.ts, src_js/utils/isSmallScreen.ts
As title:
- 9845df8f0210f58c2dddb961f8aa2db1f375bc9e: Preload the FontAwesome CSS to prevent the icons (settings, sidebar toggle) from flashing.
- 69787fd1dd2ce719edee616b7762683a28c63cb9: Fix the grammar of some code comments.
- be2a10a17dc60c9648dd698209e6db0097536b05: Run `npm audit fix`.
=> Cleanup: Preload FontAwesome, fix comment grammar, audit NPM packages

src_js/components/common/Hoverable.tsx, src_js/components/common/InlineNavButton.tsx, src_js/components/sidebar/index.tsx
I noticed that the sidebar and settings toggle buttons were anchors instead of real buttons 😅 It’s okay functionally, but is semantically incorrect (they don’t need the `href` attribute). 
This PR updates the toggle buttons to be real `<button>` elements instead of anchors.
=> Convert toggle buttons to real buttons

_layouts/spec.html
Closes #191. There's some issue caused by setting the base URL to localhost:8000 on some machines, but this is fixed by simply setting the base URL to the empty string, since in development mode URLs can start from `/`.
=> Change `base_url` to empty string

.githooks/pre-commit, .gitignore, _config.yml, _layouts/spec.html, _sass/spec/base.scss, demo/callouts.md, docs/DEV_README.md, docs/USAGE_ADVANCED.md, src_js/Config.ts, src_js/components/common/IconType.ts, src_js/components/sidebar/SidebarContent.tsx, src_js/components/sidebar/getSitemapUrls.ts, src_js/global.d.ts
Replacement for #194.
Closes #186. I wasn't able to test this very effectively because of #191, but hopefully it all makes sense! I edited _config.yml to include some external links and manipulate the order just for demo purposes: that should be reverted before merging this, if you decide to merge it.
@seshrs and I began a discussion in #194 at [this comment](https://github.com/eecs485staff/primer-spec/pull/194#discussion_r916418872) about what the best way would be to allow changing the order of pages in the sidebar.
=> Sidebar external and ordered links

src_js/components/main_content/useEnhancedCodeBlocks.tsx
Closes #183.
<details>
<summary>Further technical context</summary>
In #174, I modified the "Copy code" button of enhanced code blocks to instead "Copy all commands". The button would then only copy the code block lines that were not output. It would also skip the console prompt (the `$` symbol) if present in the line.
However, my code to skip the console prompt had a bug: It assumed that console commands would be wrapped in an element inside the HTML element representing the line — this is only true for lines with console prompts!
In other words, my code would only copy enhanced code block lines of this format:
```html
<td id="" class="primer-spec-code-block-line-code">
<span>
<span class="gp">$</span>
<span class="w"> </span>
</span>
<span …
```
=> [Enhanced Code Blocks] Fix multi-line console command copy behavior

demo/enhanced-code-blocks.md, src_js/components/main_content/useEnhancedCodeBlocks.tsx
Closes #175.
While working on #199, it occurred to me that I could solve #175 (whitespace support while copying `pycon` commands) in a similar fashion.
Before this PR, I used the same logic used by the line-number click handler to figure out which text contained the console prompt and which was the actual code. However, the "copy commands" button's logic does not need to be tied to the implementation details of the line-number click handler.
This PR updates the console-copy command to manually remove console prompts (and a single trailing whitespace) from each line.
Visit the preview URL at: https://preview.sesh.rs/previews/eecs485staff/primer-spec/200/demo/enhanced-code-blocks.html#pycon-console-example
I've modified the existing console example and added a new `pycon` example with this …
=> [Enhanced Code Blocks] Ignore all console prompts when copying commands

_config.yml, _layouts/spec.html, demo/long-headings.md, docs/USAGE_ADVANCED.md, src_js/Config.ts, src_js/components/sidebar/SidebarContent.tsx
This came up while transitioning EECS 485's Syllabus page to Primer Spec (https://github.com/eecs485staff/eecs485.org/pull/306). We would like to show the Sitemap on that page, but would prefer not to show a label for the Sitemap.
This PR introduces new behavior to the Sitemap: If the sitemap-label is set to the empty string in the config, we render the Sitemap without a label.
<small>
Normally, I'd classify this as a minor version bump (since we're changing assumptions in `spec.html`). However, since we're between semesters, and since Primer Spec v1.8.0 was only released a few days ago, I think it's acceptable to ship this in a patch version bump.
</small>
Change the `primerSpec.sitemap.label` field of `_config.yml` to the empty string, then rebuild the website. The Sitemap should render …
=> [Sitemap] Allow removing label from sitemap

index.md, src_js/components/sidebar/table_of_contents/__tests__/elevateHeadingSectionLevels.test.ts, src_js/components/sidebar/table_of_contents/elevateHeadingSectionLevels.ts
Closes #204.
If the page has only a single H1 heading, then that's likely the title of the page and doesn't need to be included in the Table of Contents in the Sidebar. This commit removes such a title if detected as a default behavior.
In conjunction with #205, 
_I didn't think it necessary to add an option to bypass this behavior. However, I'm happy to introduce such an option in future if needed._
I've updated the "Project 0" Demo to have a single H1 title (with all other headings being H2, etc.) The styling of headings in the Sidebar should match the Sidebar styles in eecs485staff.github.io/primer-spec.
Preview URL: PREVIEW#206
=> Remove title from TOC if necessary

_sass/spec/base.scss, _sass/spec/default_theme.scss, index.md, src_js/components/sidebar/ResizeHandle.tsx, src_js/components/sidebar/index.tsx, src_js/subthemes/Subtheme.ts, src_js/subthemes/definitions/bella.theme.ts, src_js/subthemes/definitions/default.theme.ts, src_js/subthemes/definitions/modern.theme.ts, src_js/subthemes/definitions/xcode_civic.theme.ts, src_js/utils/Storage.ts
Closes #34. I've been meaning to implement this since the very first iteration of Primer Spec, but never got around to it 😅 
This PR makes the Sidebar resizable (with minimum and maximum width constraints). The drag-handle highlights subtly when you hover between the Sidebar and the main content.
Visit PREVIEW#207 and play around with the resizable Sidebar!
- Notice how the Sidebar has minimum and maximum widths.
- Try refreshing the page. The Sidebar will render with the resized-width.
On small screens (for instance, on mobile phones), the sidebar should not be resizable.
https://user-images.githubusercontent.com/12139762/188757324-459cb159-2f42-499d-82ea-11c4e487b3ef.mov
=> Resizable sidebar

src_js/components/PrimerSpec.tsx, src_js/components/settings/index.tsx, src_js/utils/hooks/print.ts
When I first implemented the hooks for handling print events, I attempted to solve the ESLint warnings without fully understanding what I was doing.
Now that I better understand how `useCallback()` and `useEffect()` work, I was able to simplify the code a bit. We also now have fewer print-handlers registered on the page, and they update less-frequently :)
=> [Cleanup] Simply custom print hooks

.github/workflows/pages.yml, README.md
Now that GitHub Pages supports [deployments via GitHub Actions,](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow), this commit:
- Updates the README to recommend deploying Primer Spec websites using GitHub Actions.
- Uses GitHub Actions to deploy this repository's website.
Using GitHub Actions gives us two benefits:
- We can add arbitrary steps to the GitHub Actions build step (https://github.com/seshrs/build-primer-spec-action). This means that we can theoretically add arbitrary Jekyll plugins, generate PDFs (#136) and more!
- [Minor] This repository can make `develop` the main Primer Spec branch for PRs.
**Note:** This PR is labeled as a "minor" change because …
=> Use GitHub Actions to deploy GitHub Pages

demo/enhanced-code-blocks.md, docs/USAGE_ADVANCED.md, src_js/components/main_content/enhanced_code_blocks/__tests__/parseCodeHighlightRanges.test.ts, src_js/components/main_content/enhanced_code_blocks/createEnhancedCodeBlock.tsx, src_js/components/main_content/enhanced_code_blocks/parseCodeHighlightRanges.ts
While researching other static site generators in #213, I discovered a really cool syntax for highlighting code block lines in [Docusaurus](https://docusaurus.io/docs/markdown-features/code-blocks#highlighting-with-comments).
This PR adds the ability to highlight code block lines using "magic comments". Primer Spec will recognize code block lines with comments `primer-spec-highlight-start` and `primer-spec-highlight-end`, and will automatically ensure that the lines in between are highlighted!
This only works with code blocks with syntax-highlighting, and only for pages built using Jekyll.
Check out the demo preview URL: https://preview.sesh.rs/previews/eecs485staff/primer-spec/218/demo/enhanced-code-blocks.html#markdown-source-for-magic-comments-6
It contains the following code block: …
=> [Code blocks] Magic Comments to mark highlight ranges

src_js/components/main_content/enhanced_code_blocks/genCopyButton.tsx
Fixes #221.
The bug is kind-of embarrassing. When you click the "copy" button, we run a "mapping" function on each line that determines what text should be copied.
I forgot that if a line was empty, the mapping function would retun an empty string, which is "falsy" according to the `Boolean` test. I really should have explicitly checked that the map function's return value is not nullish before excluding it from the copied text. 😅
=> [Enhanced code blocks] Copy button should not omit lines with no text by default

.github/workflows/upload-develop-preview.yml, .github/workflows/upload-pr-preview.yml, _layouts/spec.html, _sass/spec/base.scss, src_js/Config.ts, src_js/components/Topbar.tsx, src_js/components/common/IconType.ts, src_js/components/common/InlineButton.tsx, src_js/components/common/openExternalLink.ts, src_js/global.d.ts
Closes #136! 🚀
As mentioned in #136, I've seen Piazza questions with students asking how to download the spec as a PDF (either because they don't know about print-to-PDF, or because they assume that the PDF won't look good). Hence, let's make the PDF version of the page easily available!
This turned out to be a complex feature, and [was only recently made possible by GitHub Pages + GitHub Actions + GitHub Support](https://github.com/eecs485staff/primer-spec/issues/136#issuecomment-1287647294).
If you're a course instructor, and your course website does not yet use [`build-primer-spec-action`](https://github.com/seshrs/build-primer-spec-action), your website's pages will not show the "Download as PDF" button.
Follow the instructions in that action's …
=> [PDF] Automatic PDF Generation

_sass/spec/base.scss
In #225, I was initially unsure why the tooltip was incorrectly styled. I discovered that the issue was because of conflicting styles with the "Copy" button from Enhanced Code blocks.
This PR fixes the styles to differentiate between the [different tooltip positions supported by Primer CSS](https://primer.style/css/components/tooltips).
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>Light mode</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>Dark mode</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> [PDF] Fix tooltip styling in dark mode

_sass/spec/base.scss
Fixes #227.
I visited PREVIEW#232, navigated to the Markdown Tips document and viewed the generated PDF.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td><img width="914" alt="Screen Shot 2022-12-23 at 4 12 49 PM" src="https://user-images.githubusercontent.com/12139762/209405998-0e716a05-7e05-4c31-94fe-f1bfdfe5f44a.png"></td>
</tr>
</table>
=> [PDF] Wrap long codeblock lines in print previews

src_js/components/main_content/enhanced_code_blocks/genCopyButton.tsx
Closes #223. Thanks @awdeorio and @ohjuny, this was a great suggestion 😃 
Visit the preview URL and try copying any of the multiline code blocks (including console blocks). A newline is appended to the copied text.
https://preview.sesh.rs/previews/eecs485staff/primer-spec/234/demo/enhanced-code-blocks.html
=> [Enhanced code blocks] Insert newline at the end of copied multi-line text

_sass/spec/base.scss, demo/enhanced-code-blocks.md
Closes #235. Honestly, I'm not yet certain why the `width` CSS property behaves like this, but I suspect that simply setting a percentage width on a child changes how the parent's width is calculated.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> [Enhanced Code Blocks] Use full width in no-line-numbers variant

demo/enhanced-code-blocks.md, src_js/components/main_content/enhanced_code_blocks/useEnhancedCodeBlocks.tsx
While browsing EECS 183's Project 1 spec, I noticed that they use single line codeblocks extensively. The line numbers look confusing! See [this section](https://eecs183.github.io/p1-recipes/#ingredient-cost-and-conversions) for example:
> <img width="1057" alt="image" src="https://user-images.githubusercontent.com/12139762/213884965-bf17bbb4-bc8b-4ab8-9d5d-15a1cde5319f.png">
This PR changes the behavior of enhanced code blocks so that _by default_, single-line codeblocks will not show line numbers.
Visit https://preview.sesh.rs/previews/eecs485staff/primer-spec/244/demo/enhanced-code-blocks.html#no-line-numbers and observe the single line codeblocks in the info callout.
> <img width="1058" alt="image" src="https://user-images.githubusercontent.com/12139762/213885034-8de58fd0-a52d-4977-8e0 …
=> [Enhanced Code Blocks] Avoid showing line numbers on single-line codeblocks

README.md
ENGR 100 class section 980 - Rocket Science now uses primer spec on its own website. 
I am also working on creating the labs and site for section 950 and will turn engr100.org into a landing page once completed. The hope is that other ENGR 100 sections can use our github org to add their own sections to our website.
=> Add ENGR 100 class to user showcase

_layouts/spec.html
Closes eecs280staff/p5-ml#183.
@amirkamil noticed that Mermaid diagrams weren't rendering on the P5 spec:
| Expected|Actual|
|--|--|
|<img width="1046" alt="Screenshot 2023-11-06 at 8 15 52 PM" src="https://github.com/eecs280staff/p5-ml/assets/2025676/55c3ea09-3c30-4702-909f-46f959e6d3bf"> | <img width="1021" alt="Screenshot 2023-11-06 at 8 14 11 PM" src="https://github.com/eecs280staff/p5-ml/assets/2025676/210e4a1e-c3b6-48f7-a0d4-59476e4174bd"> |
Digging a bit, I found https://github.com/mermaid-js/mermaid/issues/4442, which noted that the root cause was a breaking change in [v10 of MermaidJS](https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0):
> Mermaid is ESM only!
I didn't notice when adding MermaidJS support to Primer Spec, but it turned out that the documentation had let me …
=> Pin to Mermaid v9

src_js/components/PreviewDiffButton.tsx, src_js/components/PrimerSpec.tsx
I recently discovered that the W3C [provides a service to compare two HTML pages](https://services.w3.org/htmldiff). It works best when the changes are merely text and not HTML changes.
A few UMich courses [use](https://github.com/seshrs/upload-to-primer-spec-preview) [Primer Spec Preview](https://github.com/seshrs/primer-spec-preview) to build a website preview of their project specs whenever they make GitHub PRs. Hopefully, the W3C service could be helpful in reviewing large PRs.
> [!NOTE]  
> This commit updates Primer Spec to show a button that redirects to the W3 service. This button is _only_ shown on Primer Spec pages hosted on Primer Spec Preview. (Hence, this change is not expected to be visible to students.)
> <img width="1583" alt="Screenshot 2024-01-17 at 7 49 48 AM" …
=> [Primer Spec Preview] Add a button to redirect to a diff view

Gemfile, docs/USAGE_ADVANCED.md
Context: https://github.com/eecs485staff/primer-spec/issues/261
(Also raised and fixed in https://github.com/eecs370/project_1_spec/pull/29, thanks for reaching @hmuench7 and @jtc1246!)
=> Pin github_pages gem
